### ISSUE TITLE
Build fails from command line - unless I build the sln

### ISSUE THREAD

**Issue by skttl** [hlaueriksson/Community.PowerToys.Run.Plugin.Templates#2]
I'm trying to set up a GitHub action for releasing my plugin. In that action I'm trying to build the plugin project by running `dotnet build src\MyPlugin\Community.PowerToys.Run.Plugin.MyPlugin\Community.PowerToys.Run.Plugin.MyPlugin.csproj --configuration Release`

But it fails with multiple errors like `error CS0246: The type or namespace name 'Wox' could not be found (are you missing a using directive or an assembly reference?)` (also on PowerToys, ManagedCommon namespaces etc).

Weird thing is - if I build the sln with `dotnet build src\MyPlugin\MyPlugin.sln --configuration Release` everything works as expected.

Is there some kind of voodoo magic in the sln I can't see?

**Comment by hlaueriksson** [comment]
I'm able to reproduce this. Interesting 🤔

I think it's something with the `Community.PowerToys.Run.Plugin.Dependencies` package.

I get warnings in the build:

- https://github.com/hlaueriksson/Community.PowerToys.Run.Plugin.Dependencies/actions/runs/10044100519

I need to do some research on this.

**Comment by skttl** [comment]
For now I've got it working with simply building the sln. You can see an example of my workflow here:
https://github.com/skttl/ptrun-tailwindcss/blob/master/.github/workflows/release.yml

**Comment by hlaueriksson** [comment]
I think I have a fix for this.

With the help of these examples:

- <https://gist.github.com/rfuzzo/67ff76f0e4bff4fe45ce0b1005328b84>
- <https://learn.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders>

I have created a branch in `Community.PowerToys.Run.Plugin.Dependencies`:

- <https://github.com/hlaueriksson/Community.PowerToys.Run.Plugin.Dependencies/compare/main...tweaks>

I will need to do some testing... 🧪

**Comment by hlaueriksson** [comment]
I have great hopes for this PR:

- https://github.com/hlaueriksson/Community.PowerToys.Run.Plugin.Dependencies/pull/1

I guess that a new version of PowerToys will drop in November. I will merge and build a new package then.

**Comment by hlaueriksson** [comment]
@skttl version `0.86.0` of `Community.PowerToys.Run.Plugin.Dependencies` is now published:

- https://www.nuget.org/packages/Community.PowerToys.Run.Plugin.Dependencies/0.86.0

You should be able to build `.csproj` if you bump the package.

I need to update the templates to include the latest version.

**Comment by skttl** [comment]
Thanks, will try it out :)

**Comment by hlaueriksson** [comment]
@skttl This should be fixed in `0.2.0`:

- https://www.nuget.org/packages/Community.PowerToys.Run.Plugin.Templates/0.2.0
